# This is a sample configuration to run a Tripal instance with Docker-Compose.

version: '2'
services:

    web:
      image: erasche/tripal:latest
      links:
        - db:postgres
        - elasticsearch:elasticsearch
      volumes:
        - /var/www/html/sites
        - /var/www/private
        - ./data:/data:ro
      environment:
        UPLOAD_LIMIT: 20M
        MEMORY_LIMIT: 512M
        TRIPAL_GIT_CLONE_MODULES: "https://github.com/abretaud/tripal_rest_api.git https://github.com/tripal/tripal_elasticsearch.git https://github.com/tripal/tripal_analysis_interpro.git https://github.com/tripal/tripal_analysis_go.git  https://github.com/tripal/tripal_analysis_blast.git"
        TRIPAL_DOWNLOAD_MODULES: ""
        TRIPAL_ENABLE_MODULES: "tripal_analysis_blast tripal_analysis_interpro tripal_analysis_go tripal_rest_api tripal_elasticsearch"
      ports:
        - "3300:80"

    db:
      image: erasche/chado:latest
      environment:
        - POSTGRES_PASSWORD=postgres
          # The default chado image would try to install the schema on first run,
          # we just want the tools to be available.
        - INSTALL_CHADO_SCHEMA=0
      volumes:
        - /var/lib/postgresql/9.4/

    elasticsearch:
      image: elasticsearch
      environment:
        ES_JAVA_OPTS: "-Xms150m -Xmx150m"
